### ISSUE TITLE
A Bug in the Code for Computing a Normalized Laplacian Matrix

### ISSUE THREAD

**Issue by Shadow-Dream** [iakovosevdaimon/Neural-Graph-Generator#1]
I have recently been reading articles on graph generation, and it's great to come across your work utilizing the LDM method for graph generation and incorporating various condition guidance from Diffusion. It is indeed a creative approach. However, while going through the code, I noticed a potential error in computing the normalized Laplacian matrix. The code snippet in question is as follows:
![image](https://github.com/iakovosevdaimon/Neural-Graph-Generator/assets/44514810/858b0ddf-4dbe-4b1a-8583-9d06bd43da1a)
In this code snippet, it seems that DH should be computed using DH = sparse.diags(diags_sqrt).toarray(), but instead, diags is used. I attempted to run the code myself and found that the resulting matrix differs from what I understand as the normalized Laplacian matrix. I would like to inquire whether this discrepancy is intentional or if it is a bug in the code.

**Comment by iakovosevdaimon** [comment]
Thanks for your feedback! You are right
