### ISSUE TITLE
Any plan to release the well-trained model?

### ISSUE THREAD

**Issue by Tinyyuumi** [iakovosevdaimon/Neural-Graph-Generator#3]
Very good project. 
I see the AE model also need to train, so any plan to release well-trian model about AE? I can just retrain diffusion model. And which component is used for the best model, AE or VAE? Thanks!

**Comment by iakovosevdaimon** [comment]
Thanks! We used VAE instead of AE as it showed better performance during our experiment. In any case, we don't intend to release a pretrained AE.

Have a nice day!
